=== UFC-MDCC-HPC/Hash-Programming-Environment/HPE_FrontEnd/bin/hPE/xml/SAFe_workflow_V6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/SAFe_workflow_V4"
	xmlns:tns="http://www.example.org/SAFe_workflow_V4" elementFormDefault="qualified">

    <include schemaLocation=""></include>
    <include schemaLocation=""></include>
    <include schemaLocation=""></include>
    <element name="workflow" type="tns:SAFeSWL_OperationAnyType"></element>

	<complexType name="SAFeSWL_OperationManyType">
		<complexContent>
			<extension base="tns:SAFeSWL_OperationBaseType">
				<choice maxOccurs="unbounded" minOccurs="1">
					<element name="skip" type="tns:SAFeSWL_OperationBaseType"
						maxOccurs="1" minOccurs="1">
					</element>
					<element name="break" type="tns:SAFeSWL_OperationBaseType"
						maxOccurs="1" minOccurs="1">
					</element>
					<element name="continue" type="tns:SAFeSWL_OperationBaseType"
						maxOccurs="1" minOccurs="1">
					</element>
					<element name="start" type="tns:SAFeSWL_OperationPrimitiveInvokeActionAsyncType"
						maxOccurs="1" minOccurs="1">
					</element>
					<element name="wait" type="tns:SAFeSWL_OperationPrimitiveInvokeActionAsyncType"
						maxOccurs="1" minOccurs="1">
					</element>
					<element name="cancel" type="tns:SAFeSWL_OperationPrimitiveInvokeActionAsyncType"
						maxOccurs="1" minOccurs="1">
					</element>
					<element name="invoke" maxOccurs="1" minOccurs="1"
						type="tns:SAFeSWL_OperationPrimitiveInvokeActionType">
					</element>
					<element name="sequence" type="tns:SAFeSWL_OperationManyType"
						maxOccurs="1" minOccurs="1">
					</element>
					<element name="parallel" type="tns:SAFeSWL_OperationManyType"
						maxOccurs="1" minOccurs="1">
					</element>
					<element name="choice" maxOccurs="1" minOccurs="1" type="tns:SAFeSWL_OperationChoiceType">
					</element>
					<element name="iterate" maxOccurs="1" minOccurs="1">
						<complexType>
							<complexContent>
								<extension base="tns:SAFeSWL_OperationBaseType">
									<sequence>
										<element name="operation"
											type="tns:SAFeSWL_OperationManyType" maxOccurs="unbounded"
											minOccurs="1">
										</element>
									</sequence>
									<attribute name="max" type="int">
									</attribute>
									<attribute name="iter_label"
										type="string">
									</attribute>
								</extension>
							</complexContent>
						</complexType>
					</element>
				</choice>
			</extension>
		</complexContent>
	</complexType>



	<complexType name="SAFeSWL_OperationBaseType">
		<attribute name="order" type="int"></attribute>
		<attribute name="value" type="string"></attribute>
		<attribute name="oper_name" type="string"></attribute>
		<attribute name="level" type="int"></attribute>
        <attribute name="base_label" type="string"></attribute>
    </complexType>

	<complexType
		name="SAFeSWL_OperationPrimitiveInvokeActionType">
		<complexContent>
			<extension
				base="tns:SAFeSWL_OperationPrimitiveType">
				<attribute name="id_port" type="string"></attribute>
				<attribute name="action" type="string" use="required">
				</attribute>
			</extension>
		</complexContent>
	</complexType>

	<complexType
		name="SAFeSWL_OperationPrimitiveInvokeActionAsyncType">
		<complexContent>
			<extension
				base="tns:SAFeSWL_OperationPrimitiveInvokeActionType">
				<attribute name="handle_id" type="string"
					use="optional">
				</attribute>
			</extension>
		</complexContent>
	</complexType>




	<complexType name="SAFeSWL_OperationAnyType">
		<complexContent>
			<extension base="tns:SAFeSWL_OperationBaseType">
				<choice>
					<element name="skip" type="tns:SAFeSWL_OperationPrimitiveType"
						maxOccurs="1" minOccurs="1">
					</element>
					<element name="break" type="tns:SAFeSWL_OperationPrimitiveType"
						maxOccurs="1" minOccurs="1">
					</element>
					<element name="continue" type="tns:SAFeSWL_OperationPrimitiveType"
						maxOccurs="1" minOccurs="1">
					</element>
					<element name="start" type="tns:SAFeSWL_OperationPrimitiveInvokeActionAsyncType"
						maxOccurs="1" minOccurs="1">
					</element>
					<element name="wait" type="tns:SAFeSWL_OperationPrimitiveInvokeActionAsyncType"
						maxOccurs="1" minOccurs="1">
					</element>
					<element name="cancel" type="tns:SAFeSWL_OperationPrimitiveInvokeActionAsyncType"
						maxOccurs="1" minOccurs="1">
					</element>
					<element name="invoke" maxOccurs="1" minOccurs="1"
						type="tns:SAFeSWL_OperationPrimitiveInvokeActionType">
					</element>
					<element name="sequence" type="tns:SAFeSWL_OperationManyType"
						maxOccurs="1" minOccurs="1">
					</element>
					<element name="parallel" type="tns:SAFeSWL_OperationManyType"
						maxOccurs="1" minOccurs="1">
					</element>
					<element name="choice" maxOccurs="1" minOccurs="1" type="tns:SAFeSWL_OperationChoiceType">
					</element>
					<element name="iterate" maxOccurs="1" minOccurs="1" type="tns:SAFeSWL_OperationAnyType">
					</element>
				</choice>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="SAFeSWL_OperationChoiceType">
		<sequence>
			<element name="select" type="tns:SAFeSWL_SelectionGuardType" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="SAFeSWL_SelectionGuardType">
		<complexContent>
			<extension base="tns:SAFeSWL_OperationAnyType">

				<attribute name="id_port" type="string"></attribute>
				<attribute name="action" type="string"></attribute>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="SAFeSWL_OperationPrimitiveType">
		<complexContent>
			<extension base="tns:SAFeSWL_OperationBaseType"></extension>
		</complexContent>
	</complexType>
</schema>

=== UFC-MDCC-HPC/Hash-Programming-Environment/HPE_BackEnd/Run-MapReduce/CountWordsWorkflow.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:workflow xmlns:tns="http://www.example.org/SAFe_workflow_V6" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/SAFe_workflow_V6 SAFe_workflow_V6.xsd " xsi:type="tns:SAFeSWL_OperationAnyType">
  <tns:sequence>
      <tns:invoke id_port="platform_data_source" action="resolve"/>
      <tns:invoke id_port="platform_map"         action="resolve"/>
      <tns:invoke id_port="platform_reduce"      action="resolve"/>
      <tns:invoke id_port="platform_data_sink"   action="resolve"/>
      <tns:invoke id_port="source"               action="resolve"/>
      <tns:invoke id_port="splitter_input"       action="resolve"/>
      <tns:invoke id_port="splitter_output"      action="resolve"/>
      <tns:invoke id_port="mapper"               action="resolve"/>
      <tns:invoke id_port="shuffler"             action="resolve"/>
      <tns:invoke id_port="reducer"              action="resolve"/>
      <tns:invoke id_port="sink"                 action="resolve"/>
      <tns:invoke id_port="platform_data_source" action="deploy"/>
      <tns:invoke id_port="platform_map"         action="deploy"/>
      <tns:invoke id_port="platform_reduce"      action="deploy"/>
      <tns:invoke id_port="platform_data_sink"   action="deploy"/>
      <tns:invoke id_port="source"               action="deploy"/>
      <tns:invoke id_port="splitter_input"       action="deploy"/>
      <tns:invoke id_port="splitter_output"      action="deploy"/>
      <tns:invoke id_port="mapper"               action="deploy"/>
      <tns:invoke id_port="shuffler"             action="deploy"/>
      <tns:invoke id_port="reducer"              action="deploy"/>
      <tns:invoke id_port="sink"                 action="deploy"/>
      
      <tns:invoke id_port="platform_data_source" action="instantiate"/>
      <tns:invoke id_port="platform_map"         action="instantiate"/>
      <tns:invoke id_port="platform_reduce"      action="instantiate"/>
      <tns:invoke id_port="platform_data_sink"   action="instantiate"/>
      
      <tns:invoke id_port="input_pairs_source"        action="instantiate"/>
      <tns:invoke id_port="input_pairs_map"           action="instantiate"/>
      <tns:invoke id_port="local_intermediate_pairs"  action="instantiate"/>
      <tns:invoke id_port="global_intermediate_pairs" action="instantiate"/>
      <tns:invoke id_port="output_pairs_reduce"       action="instantiate"/>
      <tns:invoke id_port="output_pairs_sink"         action="instantiate"/>

      <tns:invoke id_port="task_split_input_read_chunk"   action="instantiate"/>
      <tns:invoke id_port="task_split_input_perform"      action="instantiate"/>
      <tns:invoke id_port="task_split_input_chunk_ready"  action="instantiate"/>
      <tns:invoke id_port="task_map"                      action="instantiate"/>
      <tns:invoke id_port="task_shuffle_read_chunk"       action="instantiate"/>
      <tns:invoke id_port="task_shuffle_perform"          action="instantiate"/>
      <tns:invoke id_port="task_shuffle_chunk_ready"      action="instantiate"/>
      <tns:invoke id_port="task_reduce"                   action="instantiate"/>
      <tns:invoke id_port="task_split_output_read_chunk"  action="instantiate"/>
      <tns:invoke id_port="task_split_output_perform"     action="instantiate"/>
      <tns:invoke id_port="task_split_output_chunk_ready" action="instantiate"/>      
      
      <tns:invoke id_port="source"          action="instantiate"/>
      <tns:invoke id_port="splitter_input"  action="instantiate"/>
      <tns:invoke id_port="splitter_output" action="instantiate"/>
      <tns:invoke id_port="mapper"          action="instantiate"/>
      <tns:invoke id_port="shuffler"        action="instantiate"/>
      <tns:invoke id_port="reducer"         action="instantiate"/>
      <tns:invoke id_port="sink"            action="instantiate"/>

      <tns:invoke id_port="source"          action="run"/>
      <tns:invoke id_port="splitter_input"  action="run"/>
      <tns:invoke id_port="splitter_output" action="run"/>
      <tns:invoke id_port="mapper"          action="run"/>
      <tns:invoke id_port="shuffler"        action="run"/>
      <tns:invoke id_port="reducer"         action="run"/>
      <tns:invoke id_port="sink"            action="run"/>
      
	  <tns:parallel>
	  	<tns:iterate>
		  	<tns:sequence>
		  		<tns:invoke id_port="task_split_input_read_chunk" action="READ_CHUNK" />
		  		<tns:invoke id_port="task_split_input_perform" action="PERFORM" />
		  	</tns:sequence>
	  	</tns:iterate>
	  	<tns:iterate>
		  	<tns:sequence>
		  		<tns:invoke id_port="task_split_input_chunk_ready" action="CHUNK_READY" />
		  		<tns:invoke id_port="task_map" action="READ_CHUNK" />
		  		<tns:start id_port="task_map" action="PERFORM" handle_id="h1" />
		  	</tns:sequence>
	  	</tns:iterate>
	  	<tns:iterate>
		  	<tns:sequence>
		  		<tns:invoke id_port="task_map" action="CHUNK_READY" />
		  		<tns:invoke id_port="task_shuffle_read_chunk" action="READ_CHUNK" ></tns:invoke>
		  		<tns:start id_port="task_shuffle_perform" action="PERFORM" handle_id="h2" />
		  	</tns:sequence>
	  	</tns:iterate>
	  	<tns:iterate>
		  	<tns:sequence>
		  		<tns:invoke id_port="task_shuffle_chunk_ready" action="CHUNK_READY" />
		  		<tns:invoke id_port="task_reduce" action="READ_CHUNK" />
		  		<tns:start id_port="task_reduce" action="PERFORM" handle_id="h3" />
		  	</tns:sequence>
	  	</tns:iterate>
	  	<tns:iterate>
		  	<tns:sequence>
		  		<tns:invoke id_port="task_reduce" action="CHUNK_READY" />
		  		<tns:invoke id_port="task_split_output_read_chunk" action="READ_CHUNK" />
		  		<tns:start id_port="task_split_output_perform" action="PERFORM" handle_id="h4" />
		  	</tns:sequence>
	  	</tns:iterate>
	  	<tns:iterate>
	  		<tns:invoke id_port="task_split_output_chunk_ready" action="CHUNK_READY" />
	  	</tns:iterate>
  	</tns:parallel>
  </tns:sequence>
</tns:workflow>
