=== UFC-MDCC-HPC/Hash-Programming-Environment/HPECommandLine/src/hpe_cmd.dtd
<!ELEMENT hpe (namespace,java+)>
<!ELEMENT namespace (#PCDATA)>
<!ELEMENT java (value,option+,argument+)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT argument (type, cardinality)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT cardinality (#PCDATA)>
<!ELEMENT option (cp+)>
<!ELEMENT cp (value,list+)>
<!ELEMENT list (argument+)>

=== UFC-MDCC-HPC/Hash-Programming-Environment/HPECommandLine/src/hpe_cmd.xml
<?xml version="1.0"?>
<!DOCTYPE bank SYSTEM "hpe_cmd.dtd" >
<hpe>
	<namespace> br.ufc.hpe </namespace>
	<java>
		<value>java</value>
		<option>
			<cp>
				<value> -cp </value>
				<list>
					<argument>
						<type> lib </type>
						<cardinality>multiple</cardinality>
					</argument>
				</list>
			</cp>
		</option>
		<argument>
			<type> java-class </type>
			<cardinality>1</cardinality>
		</argument>
	</java>
</hpe>
